from flask_restful import reqparse

checkin_parser = reqparse.RequestParser()
checkin_parser.add_argument('image_base64', type=str, required=True, help='人脸图像Base64编码不能为空')
checkin_parser.add_argument('image_format', type=str, required=True, help='图像格式不能为空')
checkin_parser.add_argument('capture_time', type=str, default=None)
checkin_parser.add_argument('device_id', type=str, default=None)
checkin_parser.add_argument('idempotency_key', type=str, default=None)
checkin_parser.add_argument('frames_base64', type=list, location='json', default=None)

attendance_query_parser = reqparse.RequestParser()
attendance_query_parser.add_argument('student_id', type=str, location='args')
attendance_query_parser.add_argument('class_name', type=str, location='args')
attendance_query_parser.add_argument('start_time', type=str, location='args')
attendance_query_parser.add_argument('end_time', type=str, location='args')
attendance_query_parser.add_argument('status', type=int, location='args')
attendance_query_parser.add_argument('cursor', type=str, location='args')
attendance_query_parser.add_argument('size', type=int, default=20, location='args')

group_photo_parser = reqparse.RequestParser()
group_photo_parser.add_argument('photo_base64', type=str, default=None)
group_photo_parser.add_argument('image_base64', type=str, default=None)
group_photo_parser.add_argument('image_format', type=str, required=True, help='图像格式不能为空')
group_photo_parser.add_argument('photo_name', type=str, default='')
group_photo_parser.add_argument('activity_name', type=str, default='')
group_photo_parser.add_argument('activity_time', type=str, default=None)

group_photo_query_parser = reqparse.RequestParser()
group_photo_query_parser.add_argument('activity_name', type=str, location='args')
group_photo_query_parser.add_argument('class_name', type=str, location='args')
group_photo_query_parser.add_argument('start_time', type=str, location='args')
group_photo_query_parser.add_argument('end_time', type=str, location='args')
group_photo_query_parser.add_argument('cursor', type=str, location='args')
group_photo_query_parser.add_argument('size', type=int, default=20, location='args')

emotion_query_parser = reqparse.RequestParser()
emotion_query_parser.add_argument('class_name', type=str, location='args')
emotion_query_parser.add_argument('student_id', type=str, location='args')
emotion_query_parser.add_argument('source_type', type=str, location='args')
emotion_query_parser.add_argument('start_time', type=str, location='args')
emotion_query_parser.add_argument('end_time', type=str, location='args')

student_create_parser = reqparse.RequestParser()
student_create_parser.add_argument('student_id', type=str, required=True, help='学号不能为空')
student_create_parser.add_argument('name', type=str, required=True, help='姓名不能为空')
student_create_parser.add_argument('class_name', type=str, required=True, help='专业不能为空')
student_create_parser.add_argument('face_image_base64', type=str, required=True, help='人脸图像不能为空')
student_create_parser.add_argument('image_format', type=str, default='jpg')
student_create_parser.add_argument('username', type=str, default=None)
student_create_parser.add_argument('password', type=str, default=None)

student_query_parser = reqparse.RequestParser()
student_query_parser.add_argument('class_name', type=str, location='args')
student_query_parser.add_argument('keyword', type=str, location='args')
student_query_parser.add_argument('page', type=int, default=1, location='args')
student_query_parser.add_argument('size', type=int, default=20, location='args')

student_update_parser = reqparse.RequestParser()
student_update_parser.add_argument('name', type=str)
student_update_parser.add_argument('class_name', type=str)
student_update_parser.add_argument('face_image_base64', type=str)
student_update_parser.add_argument('image_format', type=str, default='jpg')

login_parser = reqparse.RequestParser()
login_parser.add_argument('username', type=str, required=True, help='用户名不能为空')
login_parser.add_argument('password', type=str, required=True, help='密码不能为空')

refresh_parser = reqparse.RequestParser()
refresh_parser.add_argument('refresh_token', type=str, required=True, help='刷新令牌不能为空')

report_query_parser = reqparse.RequestParser()
report_query_parser.add_argument('class_name', type=str, location='args')
report_query_parser.add_argument('activity_name', type=str, location='args')
report_query_parser.add_argument('student_id', type=str, location='args')
report_query_parser.add_argument('start_time', type=str, location='args')
report_query_parser.add_argument('end_time', type=str, location='args')
